version: '3.8'

services:
  # Development service
  dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "7777:7777"
    command: pnpm run dev
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=7777
    networks:
      - sortvision_net
    
  # Production service
  prod:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - sortvision_net

networks:
  sortvision_net:
    driver: bridge 