services:
  # Development service
  dev:
    build:
      context: .
      target: build
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"  # Next.js default port
    command: pnpm run dev
    environment:
      - NODE_ENV=development
      - HOSTNAME=0.0.0.0
      - PORT=3000
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net
    stdin_open: true
    tty: true
    
  # Production service
  prod:
    build: .
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net
    restart: unless-stopped
    
  # Static build for testing production build locally
  build:
    build:
      context: .
      target: build
    volumes:
      - ./dist:/app/dist
    command: pnpm run build
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_GITHUB_TOKEN=${NEXT_PUBLIC_GITHUB_TOKEN:-}
    networks:
      - sortvision_net

networks:
  sortvision_net:
    driver: bridge 